### ISSUE TITLE
存在重复映射

### ISSUE THREAD

**Issue by lgernierO** [a5566123s/Calibre-BIG5toGBK#2]
重复的值：'散钱', '银鍊', '着称', '着名', '馀', '金鍊', '沈没', '甚么', '沈浮', '着作', '所着', '昭着', '卓着', '沈默', '遗着', '沈迷', '干隆', '沈积', '手鍊', '铁鍊', '脚鍊'

**Comment by lgernierO** [comment]
在1.2基础上删去了重复映射，调整腾格里
騰格里为騰格里
腾格里
[Uploading Calibre.by.a5.zip…]()

**Comment by lgernierO** [comment]
在1.2基础上删去了重复映射，调整腾格里
騰格里为騰格里
腾格里
[Calibre.by.a5.zip](https://github.com/a5566123s/Calibre-BIG5toGBK/files/13327352/Calibre.by.a5.zip)

**Comment by a5566123s** [comment]
感谢纠错
